baseURL = 'https://maths-s-website1.pages.dev/'
locale = 'en-us'
title = '断续的梦'
theme = "yinyang"
DefaultContentLanguage = "cn"

[taxonomies]
    tag = "tags"

[author]
    name = "NoDreamlogic"

[params]
    headTitle = "NoDreamlogic"
    mainSections = ["posts"]

[markup]
    [markup.goldmark.renderer]
        unsafe = true